### ISSUE TITLE
Initial Backend Setup [Database]

### ISSUE THREAD

**Issue by lecegues** [lecegues/lecegues-website#4]
### Wiki Research
- [x] - [ ] Add to wiki: How does NoSQL work?
- [x] Add to wiki: How does MongoDB work?
- [x] Add to wiki: How does Mongoose work?

### TODO
- [x] Setup MongoDB with Mongoose for your database
- [x] Integrate GraphQL for complex queries (if currently needed, otherwise do later)
- [x] Implement RESTful APIs or GraphQL queries/mutations
